osx_image: xcode10.2
language: objective-c

script:
- ./Sources/gdal/prepare_gdal.sh
- cd Tests
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -scheme Tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.2' | xcpretty
